site_name: "Terraform Provider: Keycloak"
nav:
- Getting Started:
  - Installing: index.md
- Resources:
  - keycloak_realm: resources/keycloak_realm.md
  - keycloak_user: resources/keycloak_user.md
  - keycloak_group: resources/keycloak_group.md
  - keycloak_group_memberships: resources/keycloak_group_memberships.md
  - keycloak_openid_client: resources/keycloak_openid_client.md
  - keycloak_openid_client_scope: resources/keycloak_openid_client_scope.md
  - keycloak_openid_client_default_scopes: resources/keycloak_openid_client_default_scopes.md
  - keycloak_openid_user_attribute_protocol_mapper: resources/keycloak_openid_user_attribute_protocol_mapper.md
  - keycloak_openid_user_property_protocol_mapper: resources/keycloak_openid_user_property_protocol_mapper.md
  - keycloak_openid_group_membership_protocol_mapper: resources/keycloak_openid_group_membership_protocol_mapper.md
  - keycloak_openid_hardcoded_claim_protocol_mapper:  resources/keycloak_openid_hardcoded_claim_protocol_mapper.md
theme: readthedocs
markdown_extensions:
- toc:
    toc_depth: 6
extra_css: [index.css]
