name: Build Test Image
on:
  workflow_dispatch: { }
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-test-image.yml"
      - "test/Dockerfile"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-keycloak-dev

jobs:
  build:
    #    runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
        keycloak-version:
          - '26.0.5'
          - '25.0.2'
          - '24.0.5'
          - '23.0.7'
          - '22.0.5'
          - '21.1.2'
      fail-fast: false
    concurrency:
      group: docker-build-${{ matrix.keycloak-version }}
      cancel-in-progress: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: test/Dockerfile
          build-args: |
            KEYCLOAK_VERSION=${{ matrix.keycloak-version }}
